name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "29385150-e1d136b0-40f9-4941-bca8-c2af48b0174e" -e "29385150-d2c1cc20-6ee6-4bd5-9ae8-d3d15e6a4d88" --env-var="postman-api-key=${{ secrets.POSTMAN_API_KEY }}"
